export const env = {
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "",
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY ?? "",
  STEALTHGPT_API_KEY: process.env.STEALTHGPT_API_KEY ?? "",
  TRIGGER_SECRET_KEY: process.env.TRIGGER_SECRET_KEY ?? "",
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ?? "",
  COINBASE_COMMERCE_API_KEY: process.env.COINBASE_COMMERCE_API_KEY ?? "",
  ALIPAY_APP_ID: process.env.ALIPAY_APP_ID ?? "",
  WECHAT_PAY_MERCHANT_ID: process.env.WECHAT_PAY_MERCHANT_ID ?? ""
} as const;
